# Generated by Django 2.1.3 on 2019-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='band_sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=50, verbose_name='品牌')),
                ('month', models.IntegerField(max_length=6, verbose_name='月份')),
                ('weeks', models.IntegerField(max_length=2, verbose_name='周数')),
                ('month_week', models.CharField(max_length=7, verbose_name='月周')),
                ('aidou', models.CharField(max_length=10, verbose_name='爱都')),
                ('amount_money', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='金额占比')),
                ('amount_sales', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='销量占比')),
                ('total_money', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='销售金额')),
                ('total_sales', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='销量')),
                ('visitor', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='曝光量')),
                ('total_visitor', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='行业曝光量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='平均单价')),
                ('transaction', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='转化率')),
                ('average_transaction', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='平均转化率')),
            ],
        ),
    ]
