# Generated by Django 2.1.3 on 2019-02-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band_sell',
            name='weeks',
            field=models.IntegerField(max_length=6, verbose_name='周数'),
        ),
    ]
