# Generated by Django 2.1.3 on 2019-02-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_data', '0003_auto_20190227_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band_sell',
            name='average_transaction',
            field=models.CharField(max_length=7, verbose_name='平均转化率'),
        ),
        migrations.AlterField(
            model_name='band_sell',
            name='transaction',
            field=models.CharField(max_length=7, verbose_name='转化率'),
        ),
    ]
